import type { DashboardResponse } from "@/types/kpi";

export const MOCK_API_RESPONSE: DashboardResponse = {
  meta: {
    timestamp: new Date().toISOString(),
    status: "online",
  },
  data: {
    eta: {
      kpis: [
        // --- OPERACIONAIS ---
        // Fluxo Alimentação (m³/h) e (m³/dia)
        {
          id: "eta_fluxo_alimentacao_m3h",
          label: "Fluxo de Alimentação — Vazão de Água de Entrada",
          value: 150,
          unit: "m³/h",
          limit: null,
          category: "operacional",
          updated_at: new Date().toISOString(),
        },
        {
          id: "eta_fluxo_alimentacao_m3d",
          label: "Fluxo de Alimentação — Vazão de Água de Entrada",
          value: 3600,
          unit: "m³/dia",
          limit: null,
          category: "operacional",
          updated_at: new Date().toISOString(),
        },

        // Fluxo Retrolavagem (m³/h) e (m³/dia)
        {
          id: "eta_fluxo_retrolavagem_m3h",
          label: "Fluxo Retrolavagem — Vazão de Água Filtrada",
          value: 80,
          unit: "m³/h",
          limit: null,
          category: "operacional",
          updated_at: new Date().toISOString(),
        },
        {
          id: "eta_fluxo_retrolavagem_m3d",
          label: "Fluxo Retrolavagem — Vazão de Água Filtrada",
          value: 1920,
          unit: "m³/dia",
          limit: null,
          category: "operacional",
          updated_at: new Date().toISOString(),
        },

        // Tempo de Filtração entre Retrolavagens (h e dias)
        {
          id: "eta_tempo_filtracao_h",
          label: "Tempo de Filtração entre Retrolavagens",
          value: 12,
          unit: "h",
          limit: null,
          category: "operacional",
          updated_at: new Date().toISOString(),
        },
        {
          id: "eta_tempo_filtracao_d",
          label: "Tempo de Filtração entre Retrolavagens",
          value: 0.5,
          unit: "dias",
          limit: null,
          category: "operacional",
          updated_at: new Date().toISOString(),
        },

        // Outros operacionais ETA
        {
          id: "eta_consumo_especifico_energia",
          label: "Consumo Específico de Energia",
          value: 0.45,
          unit: "kWh/m³",
          limit: null,
          category: "operacional",
          updated_at: new Date().toISOString(),
        },
        {
          id: "eta_descartes_lodo",
          label: "Tempos de Descartes de Lodo",
          value: 3,
          unit: "ciclos/dia",
          limit: null,
          category: "operacional",
          updated_at: new Date().toISOString(),
        },
        {
          id: "eta_velocidade_floculadores",
          label: "Velocidade dos Floculadores",
          value: 35,
          unit: "rpm",
          limit: null,
          category: "operacional",
          updated_at: new Date().toISOString(),
        },
        {
          id: "eta_bombas_atividade",
          label: "Bombas em Atividade",
          value: 2,
          unit: "qtd",
          limit: null,
          category: "operacional",
          updated_at: new Date().toISOString(),
        },
        {
          id: "eta_volume_produtos_quimicos",
          label: "Volumes Tanques Produtos Químicos",
          value: 70,
          unit: "%",
          limit: null,
          category: "operacional",
          updated_at: new Date().toISOString(),
        },
        {
          id: "eta_nivel_filtros",
          label: "Nível dos Filtros",
          value: 60,
          unit: "%",
          limit: null,
          category: "operacional",
          updated_at: new Date().toISOString(),
        },
        {
          id: "eta_nivel_bruta",
          label: "Nível Tanque Água Bruta",
          value: 75,
          unit: "%",
          limit: null,
          category: "operacional",
          updated_at: new Date().toISOString(),
        },
        {
          id: "eta_nivel_filtrada",
          label: "Nível Caixa Água Filtrada",
          value: 80,
          unit: "%",
          limit: null,
          category: "operacional",
          updated_at: new Date().toISOString(),
        },
        {
          id: "eta_nivel_recuperada",
          label: "Nível Caixa Água Recuperada",
          value: 50,
          unit: "%",
          limit: null,
          category: "operacional",
          updated_at: new Date().toISOString(),
        },

        // --- QUALIDADE DA ÁGUA ---
        {
          id: "eta_turbidez_filtrada",
          label: "Turbidez Água Filtrada",
          value: 0.82,
          unit: "NTU",
          limit: null,
          category: "qualidade_da_agua",
          updated_at: new Date().toISOString(),
        },
        {
          id: "eta_cloro_filtrada",
          label: "Cloro Água Filtrada",
          value: 1.2,
          unit: "mg/L",
          limit: null,
          category: "qualidade_da_agua",
          updated_at: new Date().toISOString(),
        },

        // --- LIMPEZA E MANUTENÇÃO ---
        {
          id: "eta_freq_retrolavagem",
          label: "Frequência de Retrolavagens",
          value: 28,
          unit: "ciclos/mês",
          limit: null,
          category: "limpeza_e_manutencao",
          updated_at: new Date().toISOString(),
        },
        {
          id: "eta_freq_descarte_lodo",
          label: "Frequência Descarte de Lodo",
          value: 14,
          unit: "ciclos/mês",
          limit: null,
          category: "limpeza_e_manutencao",
          updated_at: new Date().toISOString(),
        },

        // --- INTEGRIDADE E ALARMES ---
        {
          id: "eta_taxa_alarmes",
          label: "Taxa de Alarmes Críticos",
          value: 0,
          unit: "qtd/semana",
          limit: 0,
          category: "integridade_e_alarme",
          updated_at: new Date().toISOString(),
        },
        {
          id: "eta_inatividade",
          label: "Tempo de Inatividade Não Planejada",
          value: 1,
          unit: "h/mês",
          limit: null,
          category: "integridade_e_alarme",
          updated_at: new Date().toISOString(),
        },
      ],
    },
    ultrafiltracao: {
      kpis: [
        // Fluxo Alimentação (m³/h) e (m³/dia)
        {
          id: "uf_fluxo_alimentacao_m3h",
          label: "Fluxo de Alimentação — Vazão de Água de Entrada",
          value: 140,
          unit: "m³/h",
          limit: null,
          category: "operacional",
          updated_at: new Date().toISOString(),
        },
        {
          id: "uf_fluxo_alimentacao_m3d",
          label: "Fluxo de Alimentação — Vazão de Água de Entrada",
          value: 3360,
          unit: "m³/dia",
          limit: null,
          category: "operacional",
          updated_at: new Date().toISOString(),
        },

        // Fluxo Permeado (m³/h) e (m³/dia)
        {
          id: "uf_fluxo_permeado_m3h",
          label: "Fluxo Permeado — Vazão do Permeado",
          value: 120,
          unit: "m³/h",
          limit: null,
          category: "operacional",
          updated_at: new Date().toISOString(),
        },
        {
          id: "uf_fluxo_permeado_m3d",
          label: "Fluxo Permeado — Vazão do Permeado",
          value: 2880,
          unit: "m³/dia",
          limit: null,
          category: "operacional",
          updated_at: new Date().toISOString(),
        },

        // Fluxo Retrolavagem (m³/h) e (m³/dia)
        {
          id: "uf_fluxo_retrolavagem_m3h",
          label: "Fluxo Retrolavagem — Vazão de Retrolavagem",
          value: 30,
          unit: "m³/h",
          limit: null,
          category: "operacional",
          updated_at: new Date().toISOString(),
        },
        {
          id: "uf_fluxo_retrolavagem_m3d",
          label: "Fluxo Retrolavagem — Vazão de Retrolavagem",
          value: 720,
          unit: "m³/dia",
          limit: null,
          category: "operacional",
          updated_at: new Date().toISOString(),
        },

        // Outros operacionais UF
        {
          id: "uf_taxa_recuperacao",
          label: "Taxa de Recuperação",
          value: 85,
          unit: "%",
          limit: null,
          category: "operacional",
          updated_at: new Date().toISOString(),
        },
        {
          id: "uf_pressao_diferencial",
          label: "Pressão Diferencial",
          value: 1.2,
          unit: "bar",
          limit: null,
          category: "operacional",
          updated_at: new Date().toISOString(),
        },
        {
          id: "uf_consumo_energia",
          label: "Consumo Específico de Energia",
          value: 0.55,
          unit: "kWh/m³",
          limit: null,
          category: "operacional",
          updated_at: new Date().toISOString(),
        },
        {
          id: "uf_tempo_filtracao_h",
          label: "Tempo de Filtração entre Limpezas",
          value: 72,
          unit: "h",
          limit: null,
          category: "operacional",
          updated_at: new Date().toISOString(),
        },
        {
          id: "uf_tempo_filtracao_d",
          label: "Tempo de Filtração entre Limpezas",
          value: 3,
          unit: "dias",
          limit: null,
          category: "operacional",
          updated_at: new Date().toISOString(),
        },
        {
          id: "uf_bombas_operacao",
          label: "Bombas em Operação",
          value: 3,
          unit: "qtd",
          limit: null,
          category: "operacional",
          updated_at: new Date().toISOString(),
        },
        {
          id: "uf_nivel_tanq_quimicos",
          label: "Nível Tanques Produtos Químicos",
          value: 60,
          unit: "%",
          limit: null,
          category: "operacional",
          updated_at: new Date().toISOString(),
        },
        {
          id: "uf_nivel_agua_bruta",
          label: "Nível Tanque Água Bruta",
          value: 70,
          unit: "%",
          limit: null,
          category: "operacional",
          updated_at: new Date().toISOString(),
        },
        {
          id: "uf_nivel_permeado",
          label: "Nível Tanque Permeado",
          value: 90,
          unit: "%",
          limit: null,
          category: "operacional",
          updated_at: new Date().toISOString(),
        },

        // --- QUALIDADE ---
        {
          id: "uf_turbidez_alimentacao",
          label: "Turbidez Alimentação",
          value: 1.5,
          unit: "NTU",
          limit: null,
          category: "qualidade_da_agua",
          updated_at: new Date().toISOString(),
        },
        {
          id: "uf_turbidez_permeado",
          label: "Turbidez Permeado",
          value: 0.1,
          unit: "NTU",
          limit: null,
          category: "qualidade_da_agua",
          updated_at: new Date().toISOString(),
        },
        {
          id: "uf_cloro_alimentacao",
          label: "Cloro Alimentação",
          value: 1.0,
          unit: "mg/L",
          limit: null,
          category: "qualidade_da_agua",
          updated_at: new Date().toISOString(),
        },
        {
          id: "uf_cloro_permeado",
          label: "Cloro Permeado",
          value: 0.8,
          unit: "mg/L",
          limit: null,
          category: "qualidade_da_agua",
          updated_at: new Date().toISOString(),
        },

        // --- LIMPEZA E MANUTENÇÃO ---
        {
          id: "uf_freq_limpezas",
          label: "Frequência de Limpezas (BW, TMC, CIP)",
          value: 6,
          unit: "ciclos/mês",
          limit: null,
          category: "limpeza_e_manutencao",
          updated_at: new Date().toISOString(),
        },

        // --- INTEGRIDADE E ALARMES ---
        {
          id: "uf_taxa_alarmes",
          label: "Taxa de Alarmes Críticos",
          value: 1,
          unit: "qtd/semana",
          limit: null,
          category: "integridade_e_alarme",
          updated_at: new Date().toISOString(),
        },
        {
          id: "uf_teste_integridade",
          label: "Teste Integridade da Membrana",
          value: 1,
          unit: "",
          limit: null,
          category: "integridade_e_alarme",
          updated_at: new Date().toISOString(),
        },
        {
          id: "uf_inatividade",
          label: "Tempo de Inatividade Não Planejada",
          value: 2,
          unit: "h/mês",
          limit: null,
          category: "integridade_e_alarme",
          updated_at: new Date().toISOString(),
        },
      ],
    },
    carvao: {
      kpis: [
        // Fluxo Alimentação (m³/h) e (m³/dia)
        {
          id: "fca_fluxo_alimentacao_m3h",
          label: "Fluxo de Alimentação — Vazão de Água de Entrada",
          value: 100,
          unit: "m³/h",
          limit: null,
          category: "operacional",
          updated_at: new Date().toISOString(),
        },
        {
          id: "fca_fluxo_alimentacao_m3d",
          label: "Fluxo de Alimentação — Vazão de Água de Entrada",
          value: 2400,
          unit: "m³/dia",
          limit: null,
          category: "operacional",
          updated_at: new Date().toISOString(),
        },

        // Fluxo Retrolavagem (m³/h) e (m³/dia)
        {
          id: "fca_fluxo_retrolavagem_m3h",
          label: "Fluxo Retrolavagem — Vazão de Água Filtrada",
          value: 40,
          unit: "m³/h",
          limit: null,
          category: "operacional",
          updated_at: new Date().toISOString(),
        },
        {
          id: "fca_fluxo_retrolavagem_m3d",
          label: "Fluxo Retrolavagem — Vazão de Água Filtrada",
          value: 960,
          unit: "m³/dia",
          limit: null,
          category: "operacional",
          updated_at: new Date().toISOString(),
        },

        // Outros operacionais FC
        {
          id: "fca_consumo_energia",
          label: "Consumo Específico de Energia",
          value: 0.5,
          unit: "kWh/m³",
          limit: null,
          category: "operacional",
          updated_at: new Date().toISOString(),
        },
        {
          id: "fca_tempo_filtracao_h",
          label: "Tempo Filtração Entre Retrolavagens",
          value: 10,
          unit: "h",
          limit: null,
          category: "operacional",
          updated_at: new Date().toISOString(),
        },
        {
          id: "fca_tempo_filtracao_d",
          label: "Tempo Filtração Entre Retrolavagens",
          value: 0.42,
          unit: "dias",
          limit: null,
          category: "operacional",
          updated_at: new Date().toISOString(),
        },
        {
          id: "fca_freq_sanit_quente",
          label: "Frequência Sanitizações a Quente",
          value: 2,
          unit: "ciclos/mês",
          limit: null,
          category: "operacional",
          updated_at: new Date().toISOString(),
        },
        {
          id: "fca_pressao_diferencial",
          label: "Pressão Diferencial",
          value: 0.8,
          unit: "bar",
          limit: null,
          category: "operacional",
          updated_at: new Date().toISOString(),
        },
        {
          id: "fca_bombas_atividade",
          label: "Bombas em Atividade",
          value: 2,
          unit: "qtd",
          limit: null,
          category: "operacional",
          updated_at: new Date().toISOString(),
        },
        {
          id: "fca_status_filtro",
          label: "Status do Filtro",
          value: null,
          unit: null, 
          limit: null,
          status_operation: "operação",
          category: "operacional",
          updated_at: new Date().toISOString(),
        },
        {
          id: "fca_nivel_semi_tratada",
          label: "Nível Água Semi Tratada",
          value: 55,
          unit: "%",
          limit: null,
          category: "operacional",
          updated_at: new Date().toISOString(),
        },
        {
          id: "fca_nivel_recuperada",
          label: "Nível Água Recuperada",
          value: 70,
          unit: "%",
          limit: null,
          category: "operacional",
          updated_at: new Date().toISOString(),
        },

        // --- QUALIDADE ---
        {
          id: "fca_turbidez_filtrada",
          label: "Turbidez Água Filtrada",
          value: 0.5,
          unit: "NTU",
          limit: null,
          category: "qualidade_da_agua",
          updated_at: new Date().toISOString(),
        },
        {
          id: "fca_cloro_filtrada",
          label: "Cloro Água Filtrada",
          value: 1.1,
          unit: "mg/L",
          limit: null,
          category: "qualidade_da_agua",
          updated_at: new Date().toISOString(),
        },
        {
          id: "fca_temperatura_filtros",
          label: "Temperatura Filtros Carvão",
          value: 22,
          unit: "°C",
          limit: null,
          category: "qualidade_da_agua",
          updated_at: new Date().toISOString(),
        },

        // --- LIMPEZA E MANUTENÇÃO ---
        {
          id: "fca_freq_retrolavagem",
          label: "Frequência de Retrolavagens",
          value: 20,
          unit: "ciclos/mês",
          limit: null,
          category: "limpeza_e_manutencao",
          updated_at: new Date().toISOString(),
        },
        {
          id: "fca_freq_sanitizacoes",
          label: "Frequência de Sanitizações",
          value: 4,
          unit: "ciclos/mês",
          limit: null,
          category: "limpeza_e_manutencao",
          updated_at: new Date().toISOString(),
        },

        // --- INTEGRIDADE E ALARMES ---
        {
          id: "fca_taxa_alarmes",
          label: "Taxa de Alarmes Críticos",
          value: 0,
          unit: "qtd/semana",
          limit: null,
          category: "integridade_e_alarme",
          updated_at: new Date().toISOString(),
        },
        {
          id: "fca_inatividade",
          label: "Tempo de Inatividade Não Planejada",
          value: 1,
          unit: "h/mês",
          limit: null,
          category: "integridade_e_alarme",
          updated_at: new Date().toISOString(),
        },
      ],
    },
  },
};
