FROM python:3.12-slim

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY streamlit_eta_app.py .
# porta do Render vai via variável $PORT
CMD ["streamlit", "run", "streamlit_eta_app.py", "--server.port", "8501", "--server.address", "0.0.0.0"]
