# streamlit/Dockerfile
FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1 \
    PORT=8080 \
    TZ=America/Fortaleza

WORKDIR /app

# deps de sistema para psycopg2
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# instala as libs do app (use o requirements.txt da pasta streamlit)
COPY streamlit/requirements.txt .
RUN pip install -r requirements.txt

# copia somente os arquivos do app
COPY streamlit/ .

EXPOSE 8080

# rode seu arquivo correto (pelo screenshot é streamlit_eta_app.py)
CMD ["streamlit", "run", "streamlit_eta_app.py", "--server.port=${PORT}", "--server.address=0.0.0.0", "--server.enableCORS=false"]
