-- =============================================================================
-- ATENÇÃO: este arquivo NÃO é mais a fonte do schema.
--
-- O schema do banco passou a ser gerenciado por **Alembic**. A fonte autoritativa
-- e o DDL real estão em:  api/migrations/versions/0001_baseline_schema.py
-- (ver também api/migrations/README.md).
--
-- Para criar/atualizar o schema use:  alembic upgrade head
-- Para versionar uma mudança:         alembic revision -m "..."
--
-- O conteúdo anterior deste arquivo (modelo normalizado com site/unit/device/
-- gateway/raw_ingest/event/calibration) NUNCA correspondeu ao banco real — era
-- ficção. O schema REAL de produção é um modelo PLANO, resumido abaixo apenas
-- para referência rápida (o DDL fiel está na baseline do Alembic):
--
--   sensor          (id TEXT PK [seq], tag TEXT UNIQUE, unit, meta JSONB)
--   measurement     (id BIGSERIAL PK, sensor_id TEXT FK->sensor, ts, value,
--                    quality TEXT, meta JSONB, tag, unit; UNIQUE(sensor_id, ts))
--   app_user        (id SERIAL PK, email UNIQUE, name, password_hash, role,
--                    is_active, created_at)
--   user_invites    (token PK, email, created_by FK->app_user, expires_at,
--                    used, created_at)        -- TIMESTAMP sem timezone
--   config_limites  (tag PK, limite, updated_at, label)
--   config_sistema  (id PK, alarms_enabled, updated_at)
--
-- Cruft conhecido em produção (a limpar via revisão Alembic futura): tabela
-- órfã `user_invite` (singular, sem uso), UNIQUE duplicada em app_user.email,
-- e FK duplicada/conflitante em measurement.sensor_id.
-- =============================================================================
