FROM python:3.12-slim

WORKDIR /app

# instalar dependências
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# copiar todos os arquivos do worker para /app
COPY . .

# comando padrão do container
CMD ["python", "alarm_worker.py"]
